#!/usr/bin/env zsh

# A custom postprocess script is supported.

here=$0:A:h
cd $here
mkdir -p images

./screenshot.js
timestamp=$(date +%s)
humantimestamp=$(TZ=Asia/Shanghai date -d @$timestamp +%Y%m%d%H%M%S)
isodatetime=$(TZ=Asia/Shanghai date -d @$timestamp --iso-8601=s)
output=images/ticketing-$humantimestamp.png
convert ticketing.png -font Courier -pointsize 24 -gravity southwest -annotate +10+10 $isodatetime $output
optipng -silent $output
rm ticketing.png
echo $output

[[ -x postprocess ]] && postprocess $output
