#!/usr/bin/env node

const path = require('path');
const puppeteer = require('puppeteer');
const svgPath = path.resolve(process.argv[2]);
const pngPath = path.join(path.dirname(svgPath), `${path.basename(svgPath, '.svg')}@2x.png`);

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.setViewport({width: 1920, height: 1080, deviceScaleFactor: 2});
  await page.goto(`file://${svgPath}`);

  const rect = await page.evaluate(() => document.querySelector('div').getBoundingClientRect());
  await page.screenshot({path: pngPath, clip: rect});

  console.log(pngPath);
  page.close().catch(() => {});
  browser.close();
})();
